/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AboutRouteImport } from './routes/about'
import { Route as ContactRouteImport } from './routes/contact'
import { Route as HomeImprovementRouteImport } from './routes/home-improvement'
import { Route as HomeServicesRouteImport } from './routes/home-services'
import { Route as HomeWarrantyRouteImport } from './routes/home-warranty'
import { Route as PartnersRouteImport } from './routes/partners'
import { Route as PrivacyRouteImport } from './routes/privacy'
import { Route as TermsRouteImport } from './routes/terms'
import { Route as ThankYouRouteImport } from './routes/thank-you'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutRoute = AboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRouteImport,
} as any)
const ContactRoute = ContactRouteImport.update({
  id: '/contact',
  path: '/contact',
  getParentRoute: () => rootRouteImport,
} as any)
const HomeImprovementRoute = HomeImprovementRouteImport.update({
  id: '/home-improvement',
  path: '/home-improvement',
  getParentRoute: () => rootRouteImport,
} as any)
const HomeServicesRoute = HomeServicesRouteImport.update({
  id: '/home-services',
  path: '/home-services',
  getParentRoute: () => rootRouteImport,
} as any)
const HomeWarrantyRoute = HomeWarrantyRouteImport.update({
  id: '/home-warranty',
  path: '/home-warranty',
  getParentRoute: () => rootRouteImport,
} as any)
const PartnersRoute = PartnersRouteImport.update({
  id: '/partners',
  path: '/partners',
  getParentRoute: () => rootRouteImport,
} as any)
const PrivacyRoute = PrivacyRouteImport.update({
  id: '/privacy',
  path: '/privacy',
  getParentRoute: () => rootRouteImport,
} as any)
const TermsRoute = TermsRouteImport.update({
  id: '/terms',
  path: '/terms',
  getParentRoute: () => rootRouteImport,
} as any)
const ThankYouRoute = ThankYouRouteImport.update({
  id: '/thank-you',
  path: '/thank-you',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/contact': typeof ContactRoute
  '/home-improvement': typeof HomeImprovementRoute
  '/home-services': typeof HomeServicesRoute
  '/home-warranty': typeof HomeWarrantyRoute
  '/partners': typeof PartnersRoute
  '/privacy': typeof PrivacyRoute
  '/terms': typeof TermsRoute
  '/thank-you': typeof ThankYouRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/contact': typeof ContactRoute
  '/home-improvement': typeof HomeImprovementRoute
  '/home-services': typeof HomeServicesRoute
  '/home-warranty': typeof HomeWarrantyRoute
  '/partners': typeof PartnersRoute
  '/privacy': typeof PrivacyRoute
  '/terms': typeof TermsRoute
  '/thank-you': typeof ThankYouRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/contact': typeof ContactRoute
  '/home-improvement': typeof HomeImprovementRoute
  '/home-services': typeof HomeServicesRoute
  '/home-warranty': typeof HomeWarrantyRoute
  '/partners': typeof PartnersRoute
  '/privacy': typeof PrivacyRoute
  '/terms': typeof TermsRoute
  '/thank-you': typeof ThankYouRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/about'
    | '/contact'
    | '/home-improvement'
    | '/home-services'
    | '/home-warranty'
    | '/partners'
    | '/privacy'
    | '/terms'
    | '/thank-you'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/about'
    | '/contact'
    | '/home-improvement'
    | '/home-services'
    | '/home-warranty'
    | '/partners'
    | '/privacy'
    | '/terms'
    | '/thank-you'
  id:
    | '__root__'
    | '/'
    | '/about'
    | '/contact'
    | '/home-improvement'
    | '/home-services'
    | '/home-warranty'
    | '/partners'
    | '/privacy'
    | '/terms'
    | '/thank-you'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AboutRoute: typeof AboutRoute
  ContactRoute: typeof ContactRoute
  HomeImprovementRoute: typeof HomeImprovementRoute
  HomeServicesRoute: typeof HomeServicesRoute
  HomeWarrantyRoute: typeof HomeWarrantyRoute
  PartnersRoute: typeof PartnersRoute
  PrivacyRoute: typeof PrivacyRoute
  TermsRoute: typeof TermsRoute
  ThankYouRoute: typeof ThankYouRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contact': {
      id: '/contact'
      path: '/contact'
      fullPath: '/contact'
      preLoaderRoute: typeof ContactRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/home-improvement': {
      id: '/home-improvement'
      path: '/home-improvement'
      fullPath: '/home-improvement'
      preLoaderRoute: typeof HomeImprovementRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/home-services': {
      id: '/home-services'
      path: '/home-services'
      fullPath: '/home-services'
      preLoaderRoute: typeof HomeServicesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/home-warranty': {
      id: '/home-warranty'
      path: '/home-warranty'
      fullPath: '/home-warranty'
      preLoaderRoute: typeof HomeWarrantyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/partners': {
      id: '/partners'
      path: '/partners'
      fullPath: '/partners'
      preLoaderRoute: typeof PartnersRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/privacy': {
      id: '/privacy'
      path: '/privacy'
      fullPath: '/privacy'
      preLoaderRoute: typeof PrivacyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/terms': {
      id: '/terms'
      path: '/terms'
      fullPath: '/terms'
      preLoaderRoute: typeof TermsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/thank-you': {
      id: '/thank-you'
      path: '/thank-you'
      fullPath: '/thank-you'
      preLoaderRoute: typeof ThankYouRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AboutRoute: AboutRoute,
  ContactRoute: ContactRoute,
  HomeImprovementRoute: HomeImprovementRoute,
  HomeServicesRoute: HomeServicesRoute,
  HomeWarrantyRoute: HomeWarrantyRoute,
  PartnersRoute: PartnersRoute,
  PrivacyRoute: PrivacyRoute,
  TermsRoute: TermsRoute,
  ThankYouRoute: ThankYouRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
